model:
  type: base_ae_distill
  model_name: base_ae_distill
  model_kwargs:

data:
  train_data_path: ./train
  test_data_path: ./test

training_args:
  seed: 42
  use_cuda: True
  batch_size: 2
  epochs: 3000
  learning_rate: 3.0e-03
  eval_epochs: 300
  output_dir: ./artifacts
  run_name: base_ae_distill-b_2-lr_3e04
  b_t: 2