model_dir: ./artifacts/base_ae_test-b_2-lr_3e04/epoch_2659
model:
  type: base_ae
  model_name: base_ae
  model_kwargs:

data:
  train_data_path: ./train
  test_data_path: ./test

training_args:
  seed: 42
  use_cuda: True
  batch_size: 2
  epochs: 3000
  learning_rate: 3.0e-03
  eval_epochs: 380
  output_dir: ./artifacts/clusterization
  run_name: base_ae_clusterization
  b_t: 2